version: '3'

services:
  server:
    image: mexious/vm_image:latest
    container_name: instantbox_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVERURL=
    networks:
      - instantbox_net

  frontend:
    image: mexious/vm_image-frontend:latest
    container_name: instantbox_frontend
    links:
      - server
    ports:
      - 8888:80
    networks:
      - instantbox_net

  cron:
    image: xordiv/docker-alpine-cron
    container_name: instantbox_cron
    links:
      - frontend
    environment:
      - CRON_STRINGS=* * * * * wget -qO /dev/null http://frontend/api/v2/superinspire/prune
    networks:
      - instantbox_net

networks:
  instantbox_net:
