version: '3'

services:
  server:
    image: mexious/mexiousvm:latest
    container_name: mexiousvm_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVERURL=
    networks:
      - mexiousvm_net

  frontend:
    image: mexious/vm_image-frontend:latest
    container_name: mexiousvm_frontend
    links:
      - server
    ports:
      - 8877:80
    networks:
      - mexiousvm_net

  cron:
    image: xordiv/docker-alpine-cron
    container_name: mexiousvm_cron
    links:
      - frontend
    environment:
      - CRON_STRINGS=* * * * * wget -qO /dev/null http://frontend/api/v2/superinspire/prune
    networks:
      - mexiousvm_net

networks:
  mexiousvm_net:
